### ISSUE TITLE
PUT http request shall return 409 (Conflict) if one of the intermediate parent doesn't exist

### ISSUE THREAD

**Issue by AlexeyBudko** [hacdias/webdav#103]
According the specification on [PUT for non collection resource](http://www.webdav.org/specs/rfc4918.html#put-resources), if one of the intermediate parent for the requested resource doesn't exist, the WebDAV server shall return 409 (Conflict). 
But the version hacdias/webdav:v4.1.1(13 Jan 2022) on Windows 10 returns 404 (Not found) with response body 'Not Found'.

If all the intermediated parents are created, the request is performed without errors as expected.

The used config.yaml file is:

```
address: 127.0.0.1
port: 12345
auth: true
tls: false
 
users:
  - username: "Some user name"
    password: "{bcrypt}xx_some_bcrypted_password"
    modify: true
    scope: "D:/Some folder"
```
