### ISSUE TITLE
AllowedOrigin element

### ISSUE THREAD

**Issue by liang-0131** [hacdias/webdav#115]
In the AllowedOrigin element, you specify the origins that you want to allow cross-domain requests from

**Comment by mohammed90** [comment]
The [cors](https://github.com/hacdias/webdav#cors) section in the README covers this. The `allowed_hosts` key in the config maps to allowed origins.

**Comment by liang-0131** [comment]
> 
```
cors:
  enabled: true
  credentials: true
  allowed_headers:
    - Depth
  allowed_hosts:
    - app://obsidian.md
    - capacitor://localhost
    - http://localhost

  allowed_methods:
    - GET
  exposed_headers:
    - Content-Length
    - Content-Range
```
I set it like this, but I can't pass it
