### ISSUE TITLE
How can I add a all privilege user and a read only user?

### ISSUE THREAD

**Issue by xjl456852** [hacdias/webdav#120]
How do I configure it?
I tried several times without success

for example: the readonlyName user can modify,delete, update the /home folder. Cannot control this user as read-only user

```yml
address: 0.0.0.0
port: 8080
auth: true
tls: false
prefix: /
debug: false

scope: .
modify: true
rules: []

users:
  - username: xjl456852
    password: xxx
    scope: /home/
  - username: readonlyName
    password: xxx
    scope: /home/
    modify:   false

```
