### ISSUE TITLE
An error occurred when I configured multipathing with v4.2.0 version

### ISSUE THREAD

**Issue by xjl456852** [hacdias/webdav#125]
## I can't see the directory I configured.  I can only see a bin root directory, and I don't have a bin directory in my configuration

Error Detail:

![image](https://user-images.githubusercontent.com/8008097/171026211-65343b33-438f-4d13-bd6b-3cd64ce9287b.png)

![image](https://user-images.githubusercontent.com/8008097/171026309-06ea15d0-4a23-4b8d-a88e-159ce54bf48a.png)

My configuration
```yml
address: 0.0.0.0
port: 8080
auth: true
tls: false
prefix: /
debug: false

scope: .
modify: true
rules: []


users:
  - username: userName
    password: xxx
    scope: /data/b/
  - username: readonlyName
    password: xxx
    rules:
      - path: /opt/a
        modify: false
      - path: /home/
        modify: false
```
