### ISSUE TITLE
where can I find configurations documents?

### ISSUE THREAD

**Issue by jeoy** [hacdias/webdav#127]
Where can I find documents with configurations below:
```yaml
address: 0.0.0.0
port: 0
auth: true
tls: false
cert: cert.pem
key: key.pem
prefix: /
debug: false
...
```

Thanks!
