### ISSUE TITLE
Error when copying large files and how to display the specified directory

### ISSUE THREAD

**Issue by lgy1027** [hacdias/webdav#202]
Hello, may I ask
when I copy a file that is too large, and I copy a 5G compressed package, Windows will report an error, as follows
![image](https://github.com/user-attachments/assets/cd7f4e62-5afe-4a8e-b966-2b9d2e292ad5)

Please tell me how to solve this，
My configuration is as follows:

**config.yml**
```
ddress: 0.0.0.0
port: 6065

# TLS-related settings if you want to enable TLS directly.
tls: false
cert: cert.pem
key: key.pem

# Prefix to apply to the WebDAV path-ing. Default is '/'.
prefix: /

# Enable or disable debug logging. Default is 'false'.
debug: false

# Disable sniffing the files to detect their content type. Default is 'false'.
noSniff: false

# Whether the server runs behind a trusted proxy or not. When this is true,
# the header X-Forwarded-For will be used for logging the remote addresses
# of logging attempts (if available).
behindProxy: false

# The directory that will be able to be accessed by the users when connecting.
# This directory will be used by users unless they have their own 'directory' defined.
# Default is '.' (current directory).
directory: .

# The default permissions for users. This is a case insensitive option. Possible
# permissions: C (Create), R (Read), U (Update), D (Delete). You can combine multiple
# permissions. For example, to allow to read and create, set "RC". Default is "R".
permissions: CRUD

# The default permissions rules for users. Default is none.
rules: []

# Logging configuration
log:
  # Logging format ('console', 'json'). Default is 'console'.
  format: console
  # Enable or disable colors. Default is 'true'. Only applied if format is 'console'.
  colors: true
  # Logging outputs. You can have more than one output. Default is only 'stderr'.
  outputs:
  - stderr


# The list of users. If the list is empty, then there will be no authentication.
# Otherwise, basic authentication will automatically be configured.
#
# If you're delegating the authentication to a different service, you can proxy
# the username using basic authentication, and then disable webdav's password
# check using the option:
#
# noPassword: true
users:
  - username: liguoyu
    password: liguoyu3564
    permissions: CRUD
```

**docker-compose.yml**
```
version: “3”
services:
  webdav:
    image: hacdias/webdav:latest
    container_name: webdav
    restart: always
    command: ["-c", "/config.yml"]
    ports:
      - 18882:6065
    volumes:
      - /opt/lgy/fastgpt:/data
      - ./config.yml:/config.yml
```
