### ISSUE TITLE
Where should I fill in the log file path?

### ISSUE THREAD

**Issue by chouyou** [hacdias/webdav#209]
How to fill in the log file path in the configuration

**Comment by hacdias** [comment]
You can add a filepath in the `outputs` array of the `log` object in the configuration:

```
# Logging configuration
log:
  # Logging format ('console', 'json'). Default is 'console'.
  format: console
  # Enable or disable colors. Default is 'true'. Only applied if format is 'console'.
  colors: true
  # Logging outputs. You can have more than one output. Default is only 'stderr'.
  outputs:
  - stderr
```
