### ISSUE TITLE
The rules do not work per user

### ISSUE THREAD

**Issue by kookma** [hacdias/webdav#223]
I have a `.yaml` configuration file contains

```
  - username: basic
    password: basic
    # Override default permissions.
    permissions: CRUD
    rules:
      # With this rule, the user CANNOT access /some/files.
      - path: /some/file
        permissions: none
      # With this rule, the user CAN create, read, update and delete within /public/access.
      - path: /public/access/
        permissions: CRUD
      # With this rule, the user CAN read and update all files ending with .js. It uses
      # a regular expression.
      - regex: "^.+.js$"
        permissions: RU
```

The rules does not work, access to file/folders follows what is given in

```
  - username: basic
    password: basic
    # Override default permissions.
    permissions: CRUD
```

NOT in 
````
    rules:
      # With this rule, the user CANNOT access /some/files.
      - path: /some/file
        permissions: none
..
.
.
```
