### ISSUE TITLE
How to use custom config.yaml with webdav  in windows10 .

### ISSUE THREAD

**Issue by mmiker** [hacdias/webdav#45]
I'm a new user.  I  run webdav in windows 10 cmd shell.    the config.yaml is copyed from README.MD. in  the same directory.
How could I run with my custom config.yaml ? 
I tried  eg:
 d:\webdav\webdav -c config.yaml     is same return  error msg: "the environment variable is empty"
 d:\webdav\webdav -c .   the webdav is run but not use my config.yaml and can't login.   

where could found  the example ?

**Comment by sj6219** [comment]
Change the settings in the config.yaml file.

auth: false

**Comment by katana127zm** [comment]
This is because you set an "{env}" in your config file.
Just comment or delete following lines in your config file, if you dont know what it means.
``` YAML
  - username: "{env}ENV_USERNAME"
    password: "{env}ENV_PASSWORD"
```
and considering you're a new user, your config can be like this(not quite correct, but it may works for you):
```
# Server related settings
address: 0.0.0.0
port: 10010
auth: true
tls: false
cert: cert.pem
key: key.pem


# Default user settings (will be merged)
scope: .
modify: true
rules: []

# CORS configuration
cors:
  enabled: true
  credentials: true
  allowed_headers:
    - Depth
  allowed_hosts:
    - http://localhost:8080
  allowed_methods:
    - GET
  exposed_headers:
    - Content-Length
    - Content-Range

users:
  - username: admin
    password: admin
```
