### ISSUE TITLE
config multi dir

### ISSUE THREAD

**Issue by wangzhengzhen** [hacdias/webdav#56]
how config multi dir at scope?

**Comment by bAG79** [comment]
I got it like this:

```
scope: "J:/1/"
modify: false
rules: []
users:
  - username: admin
    password: 123123
#    modify:   false
    rules:
         - path: "/PONT/"
           modify: false
         - path: "/NOPONT/"
           modify: true
```
This is done for windows x64, using quotation marks for paths. Solid physical path to folders J:/1/PONT and J:/1/NOPONT
