### ISSUE TITLE
doesn't work on Windows 10 if scope is set to Disk root e.g. D:/

### ISSUE THREAD

**Issue by felix021** [hacdias/webdav#8]
works if set to subdirectories, but fails when set to disk root.

```
[Window Title]
Open Folder

[Content]
\\127.0.0.1@8086\DavWWWRoot is not acccessible. You might not have permission to use this network resource. Contact the administrator of this server .

Parameter Error


[Confirm]
```

```
scope: d:/
address: 0.0.0.0
port: 8086
tls: false
cert: cert.pem
key: key.pem
users:
  - username: admin
    password: admin
```
